# Generated by Django 5.2.8 on 2025-11-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='bus_name',
        ),
    ]
