# Generated by Django 5.2.8 on 2025-11-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_name_bus_bus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
